export enum TrackingEvents {
  VisitRiverTvWebsiteClick = "custom_visit_rivertv_website_click",
  VisitVmediaWebsiteClick = "custom_visit_vmedia_website_click",
  VisitPaxusWebsiteClick = "custom_visit_paxus_website_click",
  VisitTrikWebsiteClick = "custom_visit_trik_website_click",
  VisitKemerovoWebsiteClick = "custom_visit_kemerovo_website_click",
  VisitMyPortfolioWebsiteClick = "custom_visit_my_portfolio_website_click",
  VisitMyPortfolioRepositoryClick = "custom_visit_my_portfolio_repository_click",
  PreviewRobotsClick = "custom_preview_robots_click",
  PreviewRivertvClick = "custom_preview_rivertv_click",
  PreviewVmediaClick = "custom_preview_vmedia_click",
  PreviewPaxusClick = "custom_preview_paxus_click",
  MoreProductsClick = "custom_more_products_click",
  SwitchEnClick = "custom_switch_en_click",
  SwitchRuClick = "custom_switch_ru_click",
}
