version: "3.7"
services:
  portfolio:
    build:
      dockerfile: ./Dockerfile
      context: .
      args:
        HOST_USER_ID: ${HOST_USER_ID:-1000}
        HOST_GROUP_ID: ${HOST_GROUP_ID:-1000}
    command: /bin/sh -c "npm install && ng serve --host=0.0.0.0 --configuration=${APP_LANG:-'en'} --disable-host-check"
    ports:
      - ${SERVER_PORT:-4200}:4200
    volumes:
      - ./:/app
