services:
  portfolio:
    build:
      args:
        HOST_GROUP_ID: ${HOST_GROUP_ID:-1000}
        HOST_USER_ID: ${HOST_USER_ID:-1000}
      context: .
      dockerfile: ./Dockerfile
    command: /bin/sh -c "npm install --force && ng serve --host=0.0.0.0 --configuration=en"
    ports:
      - ${SERVER_PORT:-4200}:4200
    volumes:
      - ./:/app
version: "3.7"
