version: "3.7"
services:
  portfolio:
    build:
      dockerfile: ./docker/Dockerfile-dev
      context: .
      args:
        HOST_USER_ID: ${HOST_USER_ID:-1000}
        HOST_GROUP_ID: ${HOST_GROUP_ID:-1000}
    ports:
      - ${SERVER_PORT_EN:-4200}:4200
      - ${SERVER_PORT_RU:-4201}:4201
    volumes:
      - ./:/app
