<script lang='ts'>
import Vue from 'vue';
import Menu from './menu.vue';
import Component from 'vue-class-component'

@Component({

    components: {
        "app-menu": Menu,
    },
})
export default class Layout extends Vue {


}

</script>
<template lang='pug'>
    .content
        app-menu
        div
            | Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam ultricies tortor a lectus consequat varius. Cras orci risus, scelerisque id sagittis et, feugiat vitae lectus. Vestibulum nec mauris id arcu maximus euismod ut nec ipsum. Pellentesque bibendum, ex non congue vestibulum, tortor magna varius velit, quis placerat lorem augue sed metus. In volutpat magna dolor, nec fermentum ligula commodo eget. In feugiat eget felis ac pulvinar. Duis vel egestas est. Vivamus quam nunc, egestas non est et, ultrices feugiat lectus. Duis et mollis quam. Duis erat dui, iaculis a rutrum et, feugiat in ipsum. Sed ut diam eget ex imperdiet cursus in ac libero. Sed vitae lorem a nulla luctus molestie sit amet non augue.
            | Sed volutpat mi sed justo placerat cursus. Sed non mattis ex. Aliquam est erat, vestibulum eu aliquam sed, ultricies eget urna. Integer mauris tellus, eleifend ut turpis eget, congue faucibus velit. Vestibulum accumsan leo eu nisi tempus, in convallis mi cursus. Suspendisse laoreet tempus fringilla. In vel quam orci. Phasellus molestie lacus quis eros faucibus, in semper justo vestibulum. Nunc massa risus, ullamcorper ac ante nec, ullamcorper dapibus lectus. Donec dapibus, sapien et interdum euismod, magna massa malesuada dui, eget porta massa lacus ut ex. Curabitur neque ligula, tincidunt sit amet felis in, pharetra pellentesque risus. Aenean in justo ut sem aliquam convallis non quis sapien. Integer justo sem, feugiat quis laoreet vel, commodo in quam. Maecenas vitae fringilla urna. Etiam quam mauris, porta vitae malesuada eget, vestibulum nec lacus.
            | Morbi facilisis nec lorem in tempus. Sed eget egestas risus. Etiam posuere diam nulla, ut molestie turpis condimentum vel. Vivamus ut volutpat ex. Nunc eu commodo lacus. Phasellus nisl ipsum, porttitor viverra rutrum in, tincidunt sit amet nunc. Duis eget lacinia lacus, sed tincidunt tortor. Mauris condimentum sem eu tellus imperdiet consequat. Aliquam non varius elit, eu mattis augue. Nunc id bibendum ex. Maecenas tincidunt urna a metus posuere iaculis. Aliquam consequat sagittis felis, ac ullamcorper mi euismod eu. Suspendisse in nibh nunc. Phasellus tincidunt velit felis, vel ultricies lorem venenatis sed.
            | Maecenas euismod ex a mi ultricies congue. Nulla ut rutrum ligula. Suspendisse potenti. Donec et nisl vel lorem congue tincidunt. Donec placerat eros a tristique tempus. Nam ac risus suscipit risus aliquet consequat sed et lectus. Integer lacinia turpis et ultrices ullamcorper. Suspendisse auctor, sapien sed auctor semper, ante nibh blandit turpis, ut consequat justo velit non lorem. Fusce suscipit quam sodales justo molestie, eu blandit ex interdum.
            | Suspendisse id ligula non nibh ultricies commodo. Duis ornare vehicula ligula nec vestibulum. Sed quis viverra nisl. Curabitur maximus ex non libero laoreet, in pulvinar leo interdum. Pellentesque tincidunt nisl blandit elit pulvinar rhoncus. Quisque risus ex, ultrices eu rhoncus a, sagittis non nisl. Aliquam erat volutpat. Aenean et purus lorem. Mauris efficitur ultricies nulla, in dapibus elit venenatis at.
            | Nulla condimentum dui arcu, id pellentesque lorem vulputate imperdiet. Sed pretium pulvinar erat euismod laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Phasellus mi tortor, ornare nec urna sed, posuere efficitur justo. Donec risus turpis, vehicula ut gravida ut, cursus facilisis sapien. Aenean aliquam tellus lacus, eget vulputate diam placerat eu. Nam at libero eget sapien lacinia interdum id vitae velit. Sed id aliquam odio, non interdum odio. Donec orci nisi, pharetra vitae accumsan vitae, fermentum eget mi. Donec lacinia nec lacus id pretium. Proin volutpat enim sed erat bibendum porta. Nam nibh nisl, auctor ac magna in, aliquam egestas nisl. In aliquam lacus leo, blandit rutrum dui laoreet molestie. Phasellus aliquam massa eget ante tincidunt, sit amet suscipit ex facilisis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;
            | Praesent ut mollis enim. Aliquam viverra tortor sed mi ornare, quis egestas eros laoreet. Fusce ut sapien vitae nisi pellentesque tristique et sed urna. Nunc quam nisl, euismod ac lacus non, consequat commodo diam. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vestibulum eget lorem posuere, rutrum lacus ac, hendrerit libero. Nulla elementum est quam, sit amet vehicula turpis porttitor at. Donec tempus ut enim quis auctor. In convallis porttitor leo, eu imperdiet risus faucibus eget. Nulla metus turpis, fringilla non sem et, condimentum ullamcorper sem. Quisque quis porta enim.
            | Vivamus pulvinar porttitor erat, in luctus lorem ultricies non. Nulla dictum metus metus, et malesuada augue auctor et. Integer euismod consectetur erat, eget suscipit massa aliquet et. Cras ac ante dui. Integer dapibus imperdiet nisl, vitae cursus sapien eleifend in. Aenean semper condimentum risus a vestibulum. Morbi ac porta metus. Nulla posuere nibh erat, et posuere ante facilisis sed. Nam tempor maximus metus. Integer non mauris sed nisi varius convallis vel non est. Vestibulum at condimentum sem. Praesent tortor sapien, iaculis vel nibh auctor, cursus mollis dolor. Integer varius, eros vel tincidunt aliquam, orci justo dignissim odio, id bibendum justo turpis ut ante. Vestibulum a rhoncus justo. Sed vel odio dapibus, accumsan lacus ac, laoreet tortor.
            | Curabitur molestie, leo quis vulputate tincidunt, mauris ligula ultrices turpis, ac ornare ipsum ante vel ligula. Ut sit amet orci id mauris porttitor malesuada. Nullam vel massa leo. Praesent ac euismod nisl. Ut pharetra enim at malesuada luctus. Proin et enim sed sapien sodales imperdiet in sit amet neque. Maecenas dui risus, gravida non dictum venenatis, dictum a diam. Fusce in rhoncus elit, eu suscipit ipsum. Suspendisse in ipsum quis nisi gravida condimentum ut eu mauris. Sed quam ante, imperdiet non magna vel, cursus sollicitudin mi. Pellentesque nec metus congue, mollis nunc eu, placerat lorem. 
            | Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam ultricies tortor a lectus consequat varius. Cras orci risus, scelerisque id sagittis et, feugiat vitae lectus. Vestibulum nec mauris id arcu maximus euismod ut nec ipsum. Pellentesque bibendum, ex non congue vestibulum, tortor magna varius velit, quis placerat lorem augue sed metus. In volutpat magna dolor, nec fermentum ligula commodo eget. In feugiat eget felis ac pulvinar. Duis vel egestas est. Vivamus quam nunc, egestas non est et, ultrices feugiat lectus. Duis et mollis quam. Duis erat dui, iaculis a rutrum et, feugiat in ipsum. Sed ut diam eget ex imperdiet cursus in ac libero. Sed vitae lorem a nulla luctus molestie sit amet non augue.
            | Sed volutpat mi sed justo placerat cursus. Sed non mattis ex. Aliquam est erat, vestibulum eu aliquam sed, ultricies eget urna. Integer mauris tellus, eleifend ut turpis eget, congue faucibus velit. Vestibulum accumsan leo eu nisi tempus, in convallis mi cursus. Suspendisse laoreet tempus fringilla. In vel quam orci. Phasellus molestie lacus quis eros faucibus, in semper justo vestibulum. Nunc massa risus, ullamcorper ac ante nec, ullamcorper dapibus lectus. Donec dapibus, sapien et interdum euismod, magna massa malesuada dui, eget porta massa lacus ut ex. Curabitur neque ligula, tincidunt sit amet felis in, pharetra pellentesque risus. Aenean in justo ut sem aliquam convallis non quis sapien. Integer justo sem, feugiat quis laoreet vel, commodo in quam. Maecenas vitae fringilla urna. Etiam quam mauris, porta vitae malesuada eget, vestibulum nec lacus.
            | Morbi facilisis nec lorem in tempus. Sed eget egestas risus. Etiam posuere diam nulla, ut molestie turpis condimentum vel. Vivamus ut volutpat ex. Nunc eu commodo lacus. Phasellus nisl ipsum, porttitor viverra rutrum in, tincidunt sit amet nunc. Duis eget lacinia lacus, sed tincidunt tortor. Mauris condimentum sem eu tellus imperdiet consequat. Aliquam non varius elit, eu mattis augue. Nunc id bibendum ex. Maecenas tincidunt urna a metus posuere iaculis. Aliquam consequat sagittis felis, ac ullamcorper mi euismod eu. Suspendisse in nibh nunc. Phasellus tincidunt velit felis, vel ultricies lorem venenatis sed.
            | Maecenas euismod ex a mi ultricies congue. Nulla ut rutrum ligula. Suspendisse potenti. Donec et nisl vel lorem congue tincidunt. Donec placerat eros a tristique tempus. Nam ac risus suscipit risus aliquet consequat sed et lectus. Integer lacinia turpis et ultrices ullamcorper. Suspendisse auctor, sapien sed auctor semper, ante nibh blandit turpis, ut consequat justo velit non lorem. Fusce suscipit quam sodales justo molestie, eu blandit ex interdum.
            | Suspendisse id ligula non nibh ultricies commodo. Duis ornare vehicula ligula nec vestibulum. Sed quis viverra nisl. Curabitur maximus ex non libero laoreet, in pulvinar leo interdum. Pellentesque tincidunt nisl blandit elit pulvinar rhoncus. Quisque risus ex, ultrices eu rhoncus a, sagittis non nisl. Aliquam erat volutpat. Aenean et purus lorem. Mauris efficitur ultricies nulla, in dapibus elit venenatis at.
            | Nulla condimentum dui arcu, id pellentesque lorem vulputate imperdiet. Sed pretium pulvinar erat euismod laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Phasellus mi tortor, ornare nec urna sed, posuere efficitur justo. Donec risus turpis, vehicula ut gravida ut, cursus facilisis sapien. Aenean aliquam tellus lacus, eget vulputate diam placerat eu. Nam at libero eget sapien lacinia interdum id vitae velit. Sed id aliquam odio, non interdum odio. Donec orci nisi, pharetra vitae accumsan vitae, fermentum eget mi. Donec lacinia nec lacus id pretium. Proin volutpat enim sed erat bibendum porta. Nam nibh nisl, auctor ac magna in, aliquam egestas nisl. In aliquam lacus leo, blandit rutrum dui laoreet molestie. Phasellus aliquam massa eget ante tincidunt, sit amet suscipit ex facilisis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;
            | Praesent ut mollis enim. Aliquam viverra tortor sed mi ornare, quis egestas eros laoreet. Fusce ut sapien vitae nisi pellentesque tristique et sed urna. Nunc quam nisl, euismod ac lacus non, consequat commodo diam. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vestibulum eget lorem posuere, rutrum lacus ac, hendrerit libero. Nulla elementum est quam, sit amet vehicula turpis porttitor at. Donec tempus ut enim quis auctor. In convallis porttitor leo, eu imperdiet risus faucibus eget. Nulla metus turpis, fringilla non sem et, condimentum ullamcorper sem. Quisque quis porta enim.
            | Vivamus pulvinar porttitor erat, in luctus lorem ultricies non. Nulla dictum metus metus, et malesuada augue auctor et. Integer euismod consectetur erat, eget suscipit massa aliquet et. Cras ac ante dui. Integer dapibus imperdiet nisl, vitae cursus sapien eleifend in. Aenean semper condimentum risus a vestibulum. Morbi ac porta metus. Nulla posuere nibh erat, et posuere ante facilisis sed. Nam tempor maximus metus. Integer non mauris sed nisi varius convallis vel non est. Vestibulum at condimentum sem. Praesent tortor sapien, iaculis vel nibh auctor, cursus mollis dolor. Integer varius, eros vel tincidunt aliquam, orci justo dignissim odio, id bibendum justo turpis ut ante. Vestibulum a rhoncus justo. Sed vel odio dapibus, accumsan lacus ac, laoreet tortor.
            | Curabitur molestie, leo quis vulputate tincidunt, mauris ligula ultrices turpis, ac ornare ipsum ante vel ligula. Ut sit amet orci id mauris porttitor malesuada. Nullam vel massa leo. Praesent ac euismod nisl. Ut pharetra enim at malesuada luctus. Proin et enim sed sapien sodales imperdiet in sit amet neque. Maecenas dui risus, gravida non dictum venenatis, dictum a diam. Fusce in rhoncus elit, eu suscipit ipsum. Suspendisse in ipsum quis nisi gravida condimentum ut eu mauris. Sed quam ante, imperdiet non magna vel, cursus sollicitudin mi. Pellentesque nec metus congue, mollis nunc eu, placerat lorem. 
</template>
