name: CI
run-name: Performing continuous integration...
on: [push]
jobs:
  run-unit-tests:
    runs-on: node:18-alpine
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: test:ci
