name: CI
run-name: Continuous Integration (${{ github.actor }})
on: [push]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install packages
        run: npm ci
      - name: Run prettier
        run: npm run prettier
      - name: Lint code
        run: npm run lint
      - name: Lint styles
        run: npm run lint:styles
      - name: Run unit tests
        run: npm run test:ci
      - name: Create default config
        run: cp ./src/environments/environment.example.ts ./src/environments/environment.ts
      - name: Build production bundle
        run: npm run build:prod
